//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=DataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<DistanceLog> DistanceLogs { get; set; }
        public virtual DbSet<GroupChallenge> GroupChallenges { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<PointOfInterest> PointOfInterests { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteLeaderboard> RouteLeaderboards { get; set; }
        public virtual DbSet<RouteSection> RouteSections { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserChallenge> UserChallenges { get; set; }
        public virtual DbSet<UserGroupChallenge> UserGroupChallenges { get; set; }
    }
}
