//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DistanceLog
    {
        public int logID { get; set; }

        [Required]
        [Range(0, 200, ErrorMessage = "Distance must be in the range 0 - 200 km.")]
        public double logDistance { get; set; }

        public System.DateTime dateTimeCaptured { get; set; }

        public int userID { get; set; }
    
        public virtual User User { get; set; }
    }
}
