//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GroupChallenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupChallenge()
        {
            this.UserGroupChallenges = new HashSet<UserGroupChallenge>();
        }
    
        public int groupChallengeID { get; set; }
        [Required]
        public string groupChallengeName { get; set; }
        [Required]
        public string groupChallengeDescription { get; set; }
        public double groupChallengeDistance { get; set; }
        public System.DateTime groupChallengeTimeStart { get; set; }
        public System.DateTime groupChallengeTimeEnd { get; set; }
        public string groupChallengeGender { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a positive integer Number")]
        public int groupChallengeAgeLowerBound { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a positive integer Number")]
        public int groupChallengeAgeUpperBound { get; set; }
        public string groupChallengeDegreeYear { get; set; }
        public string groupChallengeDegreeFaculty { get; set; }
        public string groupChallengeUserType { get; set; }
        public int achievementID { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroupChallenge> UserGroupChallenges { get; set; }
    }
}
