//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.RouteSections = new HashSet<RouteSection>();
        }
    
        public int routeID { get; set; }

        [Required(ErrorMessage = "Required.")]
        public string routeName { get; set; }

        [Required(ErrorMessage = "Required.")]
        public string routeStart { get; set; }

        [Required(ErrorMessage = "Required.")]
        public string routeEnd { get; set; }

        [Required(ErrorMessage = "Required.")]
        public double distanceCovered { get; set; }

        public int achievementID { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteSection> RouteSections { get; set; }
    }
}
