//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChallenge
    {
        public int challengeID { get; set; }
        public int userID { get; set; }
        public int position { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual User User { get; set; }
    }
}
